version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: minijira-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: minijira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minijira-network

  redis:
    image: redis:7-alpine
    container_name: minijira-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - minijira-network

volumes:
  postgres_data:

networks:
  minijira-network:
    driver: bridge
