services:
  - type: web
    name: minijira-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: minijira-api-env
    autoDeploy: true
    healthCheckPath: /api/v1/health
# Notes:
# - Set up your environment variables in a group called 'minijira-api-env' in the Render dashboard.
# - The health check path should match your API's health endpoint.
# - Adjust your Dockerfile to handle build and start commands.
# - If you use a database, add a Render PostgreSQL service and set DATABASE_URL in your env group.
